os: test
build_script:
  - set PATH=C:\Ruby193\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler --no-ri --no-rdoc
  
  - set PATH=C:\Ruby200\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler --no-ri --no-rdoc
  
  - set PATH=C:\Ruby200-x64\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler --no-ri --no-rdoc
  
  - set PATH=C:\Ruby21\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler --no-ri --no-rdoc
  
  - set PATH=C:\Ruby21-x64\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler --no-ri --no-rdoc  

test: off
